int16 left_motor_pwm # motor deadzone pwm
int16 right_motor_pwm # motor deadzone pwm
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
