float32 kp # proportional term
float32 ki # intergrative term
float32 kd # derivative term
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
