name=PID_AutoTune_v0
version=1.0.0
author=Arduino Playground
maintainer=VeRLab
sentence=PID autotune library (v0)
category=Signal Input/Output
url=https://playground.arduino.cc/Code/PIDAutotuneLibrary
architectures=*
